### ISSUE TITLE
Anyone wanna do me a favor and open a GitHub issue for "silly commands having @msg.author.id instead of the author ID?[Bug] in [Feature]

### ISSUE THREAD

**Issue by HappyGothe** [chevyboys/Mizuchi#143]
**Describe the bug**
A clear and concise description of what the faulty behavior is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Workarounds:**
What (if any work arounds exist for the issue)?

**MetaData (please complete the following information):**
 - Operating System (iOS, Android, Windows, MacOS, Linux)
 - Discord platform (mobile, desktop, browser)

**Additional context**

**Comment by chevyboys** [comment]
Closed with #6aa80ea
