### ISSUE TITLE
[Text-Bug] in [/roll] description text

### ISSUE THREAD

**Issue by LanBySea** [chevyboys/Mizuchi#148]
**Describe the bug**
/roll command has description text that reads:
"roles a dice of any reasonable size"

**To Reproduce**
1. Go to "/roll"
2. See prompt text

**Expected behavior**
"roles" → "rolls"

**Screenshots**
<img width="191" alt="Screenshot 2023-05-15 at 9 59 54 AM" src="https://github.com/chevyboys/Mizuchi/assets/9815933/b9d565d1-6c02-44b1-8afb-3df0f674db9d">

Metadata:
System agnostic

**Comment by LanBySea** [comment]
https://github.com/chevyboys/Mizuchi/blob/0f9af2590287382a1cbe72fe18dc1aed4f25db74/modules/Module.Infrastructure.Register.js#LL123C29-L123C30

Managed to find the line of code, but not sure why I can't

**Comment by LanBySea** [comment]
Figured it out. See #149 

@chevyboys or @norablackcat figure one of you should make the final merge/pull as I'm still figuring things out in GitHub

**Comment by chevyboys** [comment]
Merged #149, closing issue
