### ISSUE TITLE
String overflow in Kesterbombs

### ISSUE THREAD

**Issue by King-Tersael** [chevyboys/Mizuchi#151]
**Describe the bug**
Tavare is unable to "Kester Bomb" messages that get to close to the 2000 character limit, as it must be able to add the link to the original message and is unable to in such cases.

**To Reproduce**
Attempt to bomb a message that is at or very close to the 2000 character limit.

**Expected behavior**
The bomb to succeed, though perhaps splitting is the best option

**Screenshots**
![image](https://github.com/chevyboys/Mizuchi/assets/51960830/0543186c-8a18-497f-9d19-b66c1881213b)

**Workarounds:**
Have staff member Manually add bomb

**MetaData (please complete the following information):**
 - Operating System: Linux
 - Discord platform: Desktop
 
**Additional context**
Nerp

**Comment by chevyboys** [comment]
Fixed
