### ISSUE TITLE
Incorrectly Parsed Usernames in Messages Mentioning Users

### ISSUE THREAD

**Issue by King-Tersael** [chevyboys/Mizuchi#153]
**Describe the bug**
When a user has a new form username rather than the old "discriminator" style, Tavare's messages will display the username rather than the users display name.

**To Reproduce**
Have a user that possesses a username say "Happy Pride" in General

**Expected behavior**
Tavare will need to start using Display names rather than the usernames in certain circumstances.

**Screenshots**
![image](https://github.com/chevyboys/Mizuchi/assets/51960830/cc093f46-5098-45e8-afc6-8f75abb29910)

**Workarounds:**
N/A

**MetaData (please complete the following information):**
 - Operating System: Linux
 - Discord platform: Desktop

**Additional context**
N/A

**Comment by chevyboys** [comment]
Issue was accidentally closed with the wrong PR. Our version of discord.js doesn't support the new username system, and we're already using msg.member.displayname. We're just going to have to wait for discord.js to update.
