### ISSUE TITLE
add /ask + /transfer

### ISSUE THREAD

**Issue by chevyboys** [chevyboys/Mizuchi#76]
Add the /ask and /transfer system

**Changes:**
- [ ] Commands in separate files in their own folder

- [ ] Ping all updates and question updates when rowe is answering questions

- [ ] Ask becomes /question ask
- [ ] All current commands beginning with /question- will become sub commands of /question

- [ ] /transfer becomes /question transfer and sends an embed with the username and pfp of the asker for each question. Add quick action buttons for Worldmakers:
  - [ ] Ask again some other time
  - [ ] RAFO
  - [ ] LARPers can answer this (will replace question with a new one)
  ![image](https://user-images.githubusercontent.com/17733047/166653937-1e27e89f-d8a1-498f-bc9c-f31fb559c845.png)

- [ ] Trash button becomes options button: (sends an ephemeral message with a dropdown menu)
  - Move to question discussion for non worldmaker answer (LARPers, Mod+, Worldmaker)
  - Delete 
  - Archive
  - Force vote amount
  
- [ ] Remove commands that duplicate options functionality (/question delete)

- [ ] New cooldown is 30 minutes per question in queue, when someone asks, let them know when they can ask again.

- [ ] Instead of question number, when buttons are updated, show the current position in the queue. Update each question at least once daily.

- [ ] Make utility file to handle common functions
  - [ ] Archive (instead of deleting questions after they are answered, so we can unarchive them later if needed)
  - [ ] Delete (spam/duplicate questions)
  - [ ] Ask questions (multiple ways of invoking, better just to have it in a utility file)
    - make sure ask is disabled for people who have had the smite command run on them.
  - [ ]  Generate buttons for question embeds
  - [ ]  Get all questions (sorted by current votes)
  - [ ]  Get current number of questions
  - [ ]  Create question file/data structure
  - [ ]  Set/check question based cooldowns 
 
 - [ ] Store questions in data/questions/queue and data/questions/archive

**Comment by LanBySea** [comment]
Closing this out as all functionality outlined in this has been implemented
